apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: notification-service

#
# PROFILES
#
profiles:
  - name: dev
    build:
      googleCloudBuild:
        projectId: dsgov-services
        gradleImage: gradle:7.6-jdk11-alpine
      artifacts:
        - image: us-east4-docker.pkg.dev/dsgov-services/application/dsgov-notification-service
          jib:
            type: gradle
            project: service

    deploy:
      helm:
        releases:
          - name: dsgov-notification-service
            chartPath: helm/application
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_notification_service}}"
              image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_notification_service}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_notification_service}}"
            setValues:
              environment: dev
            valuesFiles:
              - helm/application/values.dev.yaml


  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      artifacts:
        - image: notification-service
          jib:
            type: gradle
            project: service

    manifests:
      helm:
        releases:
          - name: notification-service
            chartPath: helm/application
            valuesFiles:
              - helm/application/values.local.yaml
            setValues:
              environment: local
              net.readinessProbe.initialDelaySeconds: 60
              pullPolicy: IfNotPresent
              postgres.enabled: "true"
            setValueTemplates:
              image.repository: notification-service
              image.tag: notification-service


    deploy:
      statusCheckDeadlineSeconds: 60
      tolerateFailuresUntilDeadline: true
      helm: {}

    portForward:
      - resourceType: service
        resourceName: notification-service # Change me
        namespace: dsgov
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: notification-service-postgres
        namespace: dsgov
        port: 5432
        localPort: 5438