server:
  servlet:
    context-path: /ns

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}

management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origins: ${ALLOWED_ORIGINS}
        allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allowed-headers: "*"
      exposure:
        include: "*"

auth:
  token-filter:
    self-signed:
      issuer: dsgov
      public-key: ${SELF_SIGN_PUBLIC_KEY}
  token-client:
    self-signed:
      issuer: dsgov
      private-key: ${SELF_SIGN_PRIVATE_KEY}
      roles: "um:reader, um:application-client"

cerbos:
  uri: ${CERBOS_URI}

userManagement:
  baseUrl: ${USER_MANAGEMENT_BASE_URL}