environment: "local"
namespace: "dsgov"
createIngress: true

postgres:
  enabled: false
  namespace: "dsgov"
  persistence:
    size: 1Gi
  env:
    POSTGRES_DB: "local-notification-service-db"
    POSTGRES_HOST: 'postgres-14-alpine'
    POSTGRES_PASSWORD: "root"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "root"

ingress:
  enabled: false

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 80

resources:
  notificationService:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
  cerbos:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
  pubSubEmulator:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

image:
  pullPolicy: "IfNotPresent"
  repository: "notification-service"
  tag: "latest"

net:
  host: "api.dsgov.test"
  applicationPort: 8080
  servicePort: 80
  contextPath: "/ns"
  readinessProbe:
    path: "/actuator/health"
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 10

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, http://localhost:4202, http://public.dsgov.test, http://agency.dsgov.test, http://employer.dsgov.test"
  DB_CONNECTION_URL: "jdbc:postgresql://notification-service-postgres:5432/local-notification-service-db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  EMAIL_ACCOUNT_SENDER: ""
  EMAIL_NAME_SENDER: ""
  CERBOS_URI: "127.0.0.1:3592"
  GCP_PROJECT_ID: "dsgov-dev"
  SELF_SIGN_PUBLIC_KEY: "${sm://projects/dsgov-dev/secrets/dsgov-self-signed-token-public-key/versions/latest}"
  SELF_SIGN_PRIVATE_KEY: "${sm://projects/dsgov-dev/secrets/dsgov-self-signed-token-private-key/versions/latest}"
  USER_MANAGEMENT_BASE_URL: "http://user-management/um"
  PUB_SUB_TOPIC: "projects/dsgov-dev/topics/NOTIFICATION_MSG_QUEUE"
  DEAD_LETTER_TOPIC: "projects/dsgov-dev/topics/NOTIFICATION_DEAD_LETTER"
  PUB_SUB_TOPIC_SUBSCRIPTION: "projects/dsgov-dev/subscriptions/NOTIFICATION_MSG_QUEUE_SUBSCRIPTION"
  EVENT_NOTIFICATION_TOPIC: "projects/dsgov-dev/topics/NOTIFICATION_REQUESTS"
  EVENT_NOTIFICATION_SUBSCRIPTION: "projects/dsgov-dev/subscriptions/NOTIFICATION_REQUESTS_SUBSCRIPTION"
  PUBSUB_EMULATOR_HOST: "pubsub-emulator-service:8085"
  PUBSUB_EMULATOR_ENABLED: true
  # dsgov-events publisher topics separated by comma
  PUBLISHER_TOPICS: projects/dsgov-dev/topics/APPLICATION_ROLE_REPORTING
  PUBSUB_CREATE_TOPIC: true
  TOKEN_ISSUER: "dsgov"
  TOKEN_PRIVATE_KEY_VERSION: "latest"
  TWILIO_ACCOUNT_SID: "${sm://projects/dsgov-dev/secrets/dsgov-twilio-account-sid/versions/latest}"
  TWILIO_AUTH_TOKEN: "${sm://projects/dsgov-dev/secrets/dsgov-twilio-auth-token/versions/latest}"
  TWILIO_PHONE_NUMBER: "${sm://projects/dsgov-dev/secrets/dsgov-twilio-sender-number/versions/latest}"
  SEND_GRID_EMAIL_CONTENT_TYPE: "text/html"
  SEND_GRID_EMAIL_ENDPOINT: "mail/send"
  SEND_GRID_API_KEY: "${sm://projects/dsgov-dev/secrets/dsgov-sendgrid-api-key/versions/latest}"
  SEND_GRID_SENDER: "${sm://projects/dsgov-dev/secrets/dsgov-sendgrid-sender-email/versions/latest}"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]